### ISSUE TITLE
Cannot parse IfcPropertySingleValue

### ISSUE THREAD

**Issue by TZwielehner** [IfcSharp/IfcSharpLibrary#11]
When I try to read an IFC-file (pipe example) I get an error when parsing a PropertySingleValue:
```
"Die Länge darf nicht kleiner als 0 (null) sein.\r\nParametername: length"} | System.ArgumentOutOfRangeException
```
It is the "DN" value of the pipe ("400.0000") that is not working.

**Comment by friedrichEder** [comment]
i just updated the develop-branch. some files had issues with types like IfcInteger as well, might be worth a try now ;)

**Comment by friedrichEder** [comment]
tested for multiple example files from the buildingSMART repo, did not encounter any errors. marking as closed
