### ISSUE TITLE
IFCPARAMETERVALUE is not parsed.

### ISSUE THREAD

**Issue by stevenparker3223** [IfcSharp/IfcSharpLibrary#14]
`#186= IFCTRIMMEDCURVE(#185,(IFCPARAMETERVALUE(269.874418757191)), IFCPARAMETERVALUE(285.07364578635)),.T.,.PARAMETER.);`

This is a snippet of an IFC file which causes this error below.

`ERROR on Parse2LIST.2:#186= IFCTRIMMEDCURVE(#185,(IFCPARAMETERVALUE(269.874418757191)),(IFCPARAMETERVALUE(285.07364578635)),.T.,.PARAMETER.);`

**Comment by friedrichEder** [comment]
did you try this on the development branch? there were issues with SELECT-Types which i tried to fix with the newest commit on the development branch.

**Comment by stevenparker3223** [comment]
Thanks a lot.

**Comment by friedrichEder** [comment]
did the changes in the develop-branch fix the issue?

**Comment by stevenparker3223** [comment]
I am not sure.

**Comment by friedrichEder** [comment]
tested again for mutliple files, did not encounter any errors. marking as closed
