### ISSUE TITLE
How to use your library ? 

### ISSUE THREAD

**Issue by chuongmep** [IfcSharp/IfcSharpLibrary#17]
Hi team, can I know the reason why this source missing, your team still working on process ? 
I saw so many log can't resolve 
![image](https://github.com/IfcSharp/IfcSharpLibrary/assets/31106432/f35684b4-bdda-4b47-b13b-343a3159bce8)

Thank you

**Comment by friedrichEder** [comment]
IfcSharpLibrary.csproj was not up-to-date i fixed it in the new commit. i also elaborated a bit more on the general structure an idea behind the implementation. i hope it works now for you, otherwise feel free to ask ;)

**Comment by chuongmep** [comment]
Thank you for your update, I will try it.
