### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by Moult** [IfcSharp/IfcSharpLibrary#2]
Would it be possible to specify which license is available for this project? LGPL? MIT? BSD? etc.

Love this project!

The license information would allow us to know that it is an open source project, and know how we can use it in other projects. Your project is listed on this page: https://wiki.osarch.org/index.php?title=AEC_Free_Software_directory#Software_Development

**Comment by IfcSharp** [comment]
Thank you for your comment!
Licence and how to use in other projects see: <a href="https://github.com/IfcSharp/IfcSharpLibrary/tree/master/Licence"/>

**Comment by Moult** [comment]
Thank you :) I have updated the wiki!
