### ISSUE TITLE
IFC2X3

### ISSUE THREAD

**Issue by churchij** [IfcSharp/IfcSharpLibrary#6]
Hi Bernhard,

how do you generate a schema for IFC2X3, at moment it only seems to work for IFC4X2. I can see you can include / exclude schema, but not sure how it generates different ones?

Thank you

**Comment by friedrichEder** [comment]
sorry for the late response.
if you want to build for different IFC versions, you need to change the linked ***_generated_***.cs-files in the csproj-file.
or create a specific csproj file for the IFC 2X3 version.
Just change this section in the .csproj
...

` <ItemGroup>
`    <Compile Include="IfcSchema\ifc_IFC4X2_generated_entity.cs" />
`    <Compile Include="IfcSchema\ifc_IFC4X2_generated_enum.cs" />
`    <Compile Include="IfcSchema\ifc_IFC4X2_generated_select.cs" />
`    <Compile Include="IfcSchema\ifc_IFC4X2_generated_type.cs" />
`    <Compile Include="Properties\AssemblyInfo.cs" />
`  </ItemGroup>
...

to

 `<ItemGroup>
 `   <Compile Include="IfcSchema\ifc_IFC2X3_generated_entity.cs" />
 `   <Compile Include="IfcSchema\ifc_IFC2X3_generated_enum.cs" />
 `   <Compile Include="IfcSchema\ifc_IFC2X3_generated_select.cs" />
 `   <Compile Include="IfcSchema\ifc_IFC2X3_generated_type.cs" />
 `   <Compile Include="Properties\AssemblyInfo.cs" />
 ` </ItemGroup>

this hopefully do the trick (if i understood correctly) ;)
best regards,
fritz

**Comment by bsbock** [comment]
See above, edit  IfcSpecification.csproj or use the BAT-Files in https://github.com/IfcSharp/IfcSharpApps .
