### ISSUE TITLE
"ListElement_List2to2_LengthMeasure not supportet"

### ISSUE THREAD

**Issue by TZwielehner** [IfcSharp/IfcSharpLibrary#8]
I'm trying some basic operations with this library, however, I get a few errors. I want to convert an IFC4-File to Sqlite using the following code lines:

```
Model CurrentModel = ifc.Model.FromStepFile("PATH_TO_FILE\\file.ifc");

CurrentModel.ToSqliteFile();
```

I receive the following errors (console)
_TODO List++TYPE: Base=ListElement_List2to2_LengthMeasure not supportet in_ 
followed by an IfcCartesianPointList2D. Is this not yet implemented or do I miss something here?

In Visual Studio I also get the following error:
_$exception | {"Der Konstruktor für den Typ \"ifc.Value\" wurde nicht gefunden."} | System.MissingMethodException_

**Comment by bsbock** [comment]
It is not yet implemented in Line 107 of https://github.com/IfcSharp/IfcSharpLibrary/blob/master/IfcStep/ifc_in_step.cs
Can you please post the single folowing line with an IfcCartesianPointList2D.

**Comment by friedrichEder** [comment]
i just updated the develop branch with an implementation which should be able to handle multi-dimensional lists.
keep in mind it is still under development ;)

**Comment by friedrichEder** [comment]
tested with reference examples from buildingSMART, did not encounter any erros. marking as closed
