### ISSUE TITLE
Read from step files: Errors

### ISSUE THREAD

**Issue by TZwielehner** [IfcSharp/IfcSharpLibrary#9]
I tried to import different IFC-files; however I get some errors. Code looks like this:

```
ifc.Model helloProject = ifc.Model.FromStepFile("C:\\Users\\abc\\Documents\\AC20-FZK-Haus.ifc");
```

"Der Typ "Ifc.FacetedBrep " in der Assembly "IfcSharpLibrary, Version=0.0.0.1, Culture=neutral, PublicKeyToken=null" konnte nicht geladen werden."

For other files I get a similar message concerning "Ifc.Value". (I used the "FZK house" model from https://www.ifcwiki.org/index.php?title=KIT_IFC_Examples)

**Comment by TZwielehner** [comment]
I investigated a bit further. Apparently arguments like "IFCBOOLEAN(.T.)" cannot be parsed.

**Comment by friedrichEder** [comment]
just updated the develop-branch. the FZK-Haus is now working for me
